name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: rudiedirkx/deploy-git-action@v04
        with:
          privkey: ${{ secrets.PRIVKEY }}
          host: ${{ secrets.SSH_HOST }}
          path: ${{ secrets.SSH_TARGET_DIR }}
